// DO NOT EDIT. This file is generated by remix-deno-jit.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `deno task dev`.

import * as serverEntry from "./app/entry.server.tsx";
import * as route0 from "./app/root.tsx";
import * as route1 from "./app/routes/__tests__/index.test.tsx";
import * as route2 from "./app/routes/about_.another.tsx";
import * as route3 from "./app/routes/about.nested.tsx";
import * as route4 from "./app/routes/index.tsx";
import * as route5 from "./app/routes/about.tsx";

export const entry = { module: serverEntry };
export const routes = {
	"root": {
		id: "root",
		module: route0,
		file: "./app/root.tsx",
	},
	"routes/__tests__/index/test": {
		id: "routes/__tests__/index/test",
		path: "__tests_/index/test",
		parentId: "root",
		module: route1,
		file: "./app/routes/__tests__/index.test.tsx",
	},
	"routes/about_/another": {
		id: "routes/about_/another",
		path: "about/another",
		parentId: "root",
		module: route2,
		file: "./app/routes/about_.another.tsx",
	},
	"routes/about/nested": {
		id: "routes/about/nested",
		path: "nested",
		parentId: "routes/about",
		module: route3,
		file: "./app/routes/about.nested.tsx",
	},
	"routes/index": {
		id: "routes/index",
		index: true,
		parentId: "root",
		module: route4,
		file: "./app/routes/index.tsx",
	},
	"routes/about": {
		id: "routes/about",
		path: "about",
		parentId: "root",
		module: route5,
		file: "./app/routes/about.tsx",
	},
};
export const assets = {
  entry: { imports: [], module: "/entry.client.js" },
  routes: {
		"root": {
			id: "root",
			imports: [],
			module: "/root.js",
			hasAction: "action" in route0,
			hasLoader: "loader" in route0,
			hasCatchBoundary: "CatchBoundary" in route0,
			hasErrorBoundary: "ErrorBoundary" in route0,
		},
			"routes/__tests__/index/test": {
			id: "routes/__tests__/index/test",
			path: "__tests_/index/test",
			parentId: "root",
			imports: [],
			module: "/routes/__tests__/index/test.js",
			hasAction: "action" in route1,
			hasLoader: "loader" in route1,
			hasCatchBoundary: "CatchBoundary" in route1,
			hasErrorBoundary: "ErrorBoundary" in route1,
		},
			"routes/about_/another": {
			id: "routes/about_/another",
			path: "about/another",
			parentId: "root",
			imports: [],
			module: "/routes/about_/another.js",
			hasAction: "action" in route2,
			hasLoader: "loader" in route2,
			hasCatchBoundary: "CatchBoundary" in route2,
			hasErrorBoundary: "ErrorBoundary" in route2,
		},
			"routes/about/nested": {
			id: "routes/about/nested",
			path: "nested",
			parentId: "routes/about",
			imports: [],
			module: "/routes/about/nested.js",
			hasAction: "action" in route3,
			hasLoader: "loader" in route3,
			hasCatchBoundary: "CatchBoundary" in route3,
			hasErrorBoundary: "ErrorBoundary" in route3,
		},
			"routes/index": {
			id: "routes/index",
			index: true,
			parentId: "root",
			imports: [],
			module: "/routes/index.js",
			hasAction: "action" in route4,
			hasLoader: "loader" in route4,
			hasCatchBoundary: "CatchBoundary" in route4,
			hasErrorBoundary: "ErrorBoundary" in route4,
		},
			"routes/about": {
			id: "routes/about",
			path: "about",
			parentId: "root",
			imports: [],
			module: "/routes/about.js",
			hasAction: "action" in route5,
			hasLoader: "loader" in route5,
			hasCatchBoundary: "CatchBoundary" in route5,
			hasErrorBoundary: "ErrorBoundary" in route5,
		},		
},
};
